### ISSUE TITLE
JOSS Review: sum-of-squares calculation

### ISSUE THREAD

**Issue by emilljungberg** [imr-framework/OCTOPUS#2]
In the `main_ORC.py` example code there is a sum of squares coil combination call at the very end. There seems to be a small mistake in this calculation. Currently, the line reads
```python
sos_CPR = np.sum(np.abs(CPR_result), -1)
```

It should probably be:
```python
sos_CPR = np.sqrt(np.sum(np.abs(CPR_result)**2, -1))
```

Re: [openjournals/joss-reviews/#2578](https://github.com/openjournals/joss-reviews/issues/2578)

**Comment by Mmj94** [comment]
You're right! Same mistake applies to `sos_fsCPR` and `sos_MFI`. Thank you for noticing!
Commit 23d9eb8e01c2be62698e5b0e379b0ef583f48ef4 should fix this problem, let me know and I'll close this issue.

**Comment by emilljungberg** [comment]
Thanks!
