### ISSUE TITLE
JOSS Review: Data Structures documentation

### ISSUE THREAD

**Issue by emilljungberg** [imr-framework/OCTOPUS#4]
The documentation provided for this software is very nicely outlined but it would be great to have some more information about the data structures used:

**k-space and image data**: How should these be structured? Cartesian data is quite straight forward but when it comes to non-cartesian and multi-channel/coil data it is not obvious how to structure it. A short explanation for how to structure these data would be helpful.

**non-cartesian trajectories**: Similar to the k-space and image data, description of the layout of the trajectories and which order the dimensions should be in would be very useful.

**Non-Cartesian parameter dictionary**: The NUFFT object requires a sequence parameter object that appears to be related to the trajectory. Could you please document how this dictionary should be structured?

Re: [openjournals/joss-reviews/#2578](https://github.com/openjournals/joss-reviews/issues/2578)

**Comment by Mmj94** [comment]
Please have a look at the commit above, I added some documentation to ORC.py regarding your suggestions.

**Comment by Mmj94** [comment]
Please check this commit 3e9ca4616e1f3e27580a4894755e2ee188a30849. It provides documentation regarding the data structure.

**Comment by emilljungberg** [comment]
Thanks! Yes, it does explain the data structure a lot better. Nothing that needs to change now, but looking at the code the information in the `params` dictionary overlap with the size of the k-space trajectory, so you have the same information in two places. It could potentially be slimmed down by finding those parameters from the trajectory.
