### ISSUE TITLE
B0 variation in simulations

### ISSUE THREAD

**Issue by emilljungberg** [imr-framework/OCTOPUS#7]
I was looking at the simulation study again and wondered about the large B0 variations you use in order to produce any visible off-resonance behaviour. In previously published studies, like Sutton et al. 2003 IEEE, they simulate their phantom experiment with off-resonance of +/- 60 Hz, which produce significant artefacts. The values you report, with the minimum variation of +/- 1600 Hz makes me wonder if there is some bug in the code, in terms of time/frequency units, or if the simulation isn't realistic?

One thing that I noticed is that the simulation is performed using, essentially, a zero echo time acquisition. The off-resonance accumulation in `numsim_cartesian.py` (and the non-cartesian example) is calculated to start from 0 and increase with the time step `dt=10E-6`. This would, to me, be equivalent to TE=0 and a readout bandwidth of +/- 50 kHz. This is a fairly high, but not unreasonable bandwidth, but the fact that the TE isn't included in the simulation might be the reason you are not seeing any significant off resonance artefacts at "sensible" B0 variations (+/- 100 Hz).

Would you consider including the TE in the simulation to make it more realistic and see if that makes the results to match the literature better?

Re: [openjournals/joss-reviews/#2578](https://github.com/openjournals/joss-reviews/issues/2578)

**Comment by Mmj94** [comment]
I can certainly include the TE in the simulation (please note that I have included TE for the in vitro examples). However, I do not think that this inclusion will significantly change the distortion of the images. 

As you pointed out, in Sutton et al. 2003 IEEE, the authors performed their simulations using a relatively homogenous field of +/- 60 Hz. Still, the resulting images presented significant off-resonance artifacts. However, the trajectory they used was a single-shot spiral with a readout time of approximately **19 ms**. The main effect of off-resonance is the accumulation of phase along the readout direction. For such a long trajectory, phase accrual is **3.8pi**, making off-resonance evident in the images. In the simulations we presented, we are using short readout trajectories, which are, in general, more clinically used and, therefore, more realistic. For this reason, we had to bump up the inhomogeneity to obtain noticeable distortion in the corrupted images, especially for the Cartesian case where readout time is only **1.28 ms**. 

For demonstration purposes, I came up with a similar experiment. I designed a single-shot spiral trajectory of 19 ms read-out time and used it to sample the shepp-Logan phantom image (N=64, FOV=36cm). Off-resonance was simulated using a field map with frequency range of +/- 60 Hz. In the corrupted image (figure attached), one can see significant distortion. 

![sim_singleshotspiral](https://user-images.githubusercontent.com/39202780/98731191-59ccd100-236b-11eb-87ef-00a4804813a0.png)

**Comment by emilljungberg** [comment]
Thanks for your detailed answer! That makes sense and that simulation you show here demonstrate the effect clearly.
